version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: databook
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
